In [3]:
#iris 데이터를 살펴보았다. 이젠 해당 데이터로 새로운 입력(데이터)가 주어지면  해당 데이터의 품종을 예측하려한다.
# * 중요한 점. 만든 모델을 새 데이터에 적용하기 전에
#모델 신뢰도 평가를 해야 한다. ->성능 측정
#준비된 iris 데이터 150개를 분할하여 일부는 학습하고 일부는 테스트 시험을 봐서 모델이 인반화가 되었는지 확인해 보자

import numpy as np
import pandas as pd
import mglearn
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris_dataset = load_iris()
#randaom_state로 train, test 데이터 셋을 랜덤하게 선정 -> 데이터가 균일하게 정렬되어 있어 고르게 학습 시키기 위해 데이터를 섞어 씀
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

print(X_train[:5])

[[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]]


In [5]:
print(y_train[:5])

[1 1 2 0 2]


In [4]:
print(X_test[:5])

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]]


In [6]:
print(y_test[:5])

[2 1 0 2 0]


In [7]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(112, 4) (112,) (38, 4) (38,)
